### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by jburel**
Replace travis by GHA

see https://github.com/jburel/centos-systemd-ip-docker/actions/runs/403675704
cc @sbesson

### CODE REVIEW

**Comment by sbesson** [comment]
The workflow makes sense. 

Separately, do we want to keep maintaining this image or are we moving towards deprecating it?
Most of the Ansible roles using this image previously have been updated to use `centos/systemd` image as part of the Molecule 2 upgrade. Only 2 roles are still consuming this base image, one of them being deprecated - see https://github.com/search?q=org%3Aome+centos-systemd-ip&type=code. /cc @manics

**Comment by manics** [comment]
I've no longer using this image in https://github.com/ome/ansible-role-docker/pull/9

**Comment by sbesson** [comment]
Thanks for updating @manics. Proposing to merge this and archive this repository. Objections?

**Comment by jburel** [comment]
No objections

**Pull request merged**
